apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
  nodeMeshMaxRestartTime: 120s
  asNumber: 65001
  serviceClusterIPs:
    - cidr: 10.96.0.0/12
  serviceLoadBalancerIPs:
    - cidr: 10.1.15.0/24
  listenPort: 179
  bindMode: NodeIP