apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvmpv
parameters:
  storage: "lvm"
  volgroup: "openebsvg"
provisioner: local.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer