---
- name: Upgrade csi drivers
  hosts: localhost
  tags:
  - k8s_upgrade
  - csi_upgrade

  tasks:
    - name: Install/Upgrade latest version of openebs
      kubernetes.core.helm:
        name: openebs
        chart_ref: openebs/openebs
        release_namespace: csi-openebs
        create_namespace: true
        values_files:
        - ../helm_values/openebs.yml

    - name: Ensure OpenEBS lvm StorageClass exists
      kubernetes.core.k8s:
        state: present
        src: ../k8s_manifests/openebs-lvm-storageclass.yml

    - name: Ensure OpenEBS mayastor StorageClass exists
      kubernetes.core.k8s:
        state: present
        src: ../k8s_manifests/openebs-replicated-storageclass.yml
