---
- name: Install/Upgrade kubernetes applications
  hosts: localhost
  tags:
  - gitlab_install

  tasks:
    - name: Ensure gitlab configuration db
      kubernetes.core.k8s:
        state: present
        src: ../k8s_manifests/gitlab-postgresql_j3z.yml

    - name: Install/Update gitlab helm chart
      kubernetes.core.helm:
        name: gitlab
        chart_ref: gitlab/gitlab
        release_namespace: gitlab
        create_namespace: true
        values_files:
        - ../helm_values/gitlab-values_j3z.yml